/* Generated by ps3ui get_font.sh — embedded TTF for 'Inter' weight 400. */
#ifndef inter_h_INCLUDED
#define inter_h_INCLUDED

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char inter_ttf[];
extern const unsigned int  inter_ttf_size;
extern const unsigned char inter_ttf_end[];

#ifdef __cplusplus
}
#endif

#endif
