#!/usr/bin/env bash
# embed_assets.sh — Generate source/http/embedded_assets.h from web assets.
#
# Usage: bash tools/embed_assets.sh
# Run from the project root.
#
# Produces two arrays:
#   embedded_index_html / embedded_index_html_len
#   embedded_app_js     / embedded_app_js_len

set -euo pipefail

HTML_SRC="source/web/index.html"
JS_SRC="source/web/app.js"
OUT="source/http/embedded_assets.h"

if [ ! -f "$HTML_SRC" ]; then
    echo "ERROR: $HTML_SRC not found (run from project root)" >&2
    exit 1
fi
if [ ! -f "$JS_SRC" ]; then
    echo "ERROR: $JS_SRC not found (run from project root)" >&2
    exit 1
fi

# emit_array VARNAME FILEPATH
# Writes a static unsigned char array from a file's bytes.
# Each line: up to 16 bytes as hex, comma-separated.
emit_array() {
    local varname="$1"
    local filepath="$2"
    local size
    size=$(wc -c < "$filepath" | tr -d ' ')

    echo "static const unsigned char ${varname}[] = {"

    # od: octal dump in one-byte hex format, portable across macOS+Linux
    od -v -A n -t x1 "$filepath" | \
        tr -s ' \n' '\n' | \
        grep -v '^$' | \
        awk '
            BEGIN { col = 0 }
            {
                if (col == 16) { printf "\n"; col = 0 }
                if (col == 0) printf "    "
                printf "0x%s,", $1
                col++
            }
            END { printf "\n" }
        '

    echo "};"
    echo "static const unsigned int ${varname}_len = ${size};"
    echo ""
}

{
    echo "/* Auto-generated by tools/embed_assets.sh — do not edit. */"
    echo "#ifndef SAVESYNC_EMBEDDED_ASSETS_H"
    echo "#define SAVESYNC_EMBEDDED_ASSETS_H"
    echo ""
    emit_array "embedded_index_html" "$HTML_SRC"
    emit_array "embedded_app_js"     "$JS_SRC"
    echo "#endif /* SAVESYNC_EMBEDDED_ASSETS_H */"
} > "$OUT"

echo "Generated $OUT (html=$(wc -c < "$HTML_SRC" | tr -d ' ') bytes, js=$(wc -c < "$JS_SRC" | tr -d ' ') bytes)"
